version: 2.1
orbs:
  node: circleci/node@5.1.0

workflows:
  test:
    jobs:
      - node/test:
          run-command: "test:ci"
          test-results-for: jest
      # - node/run:
          # npm-run: build
