import loadingWhite from 'assets/Logo_browse_W_60.gif'
import loadingBlack from 'assets/Logo_browse_B_60.gif'
import { ThemeSettings } from 'types/shared'

// brand colors
export const COLORS = {
  white: '#FFFFFF',
  offWhite: '#FCFBFB',
  milk: '#FEFDF9',
  darkMilk: '#F5EFE4',
  darkCream: '#F8F4E6',
  lightGray: '#DCE0E6',
  lightGray1: '#F4F4F4',
  lightGray2: '#F9F9F9',
  midGray: '#9CA1AA',
  DMMidGray: '#4F524C',
  blueGray: '#40433E',
  darkBlueGray: '#414540',
  darkGray: '#36332E',
  black: '#191713',
  yellow: '#FFBE1D',
  orange: '#F2933C',
  sage: '#B4CCC4',
  darkSage: '#6C9688',
  errorRed: '#DB362C',
  errorRed1: '#F33F3D',
  transWhite: '#FFFFFF4D',
  transBlack: '#1917134D',
}

const shadows = {
  default: '0px 4px 40px rgba(108, 150, 136, 0.2);',
}

const sizes = {
  borderRadius: '16px',
  xxs: '0.2rem',
  xs: '0.4rem',
  sm: '0.75rem',
  md: '1rem',
  lg: '1.4rem',
  xlg: '1.6rem',
  xxlg: '2.1rem',
}

const THEME: ThemeSettings = {
  Light: {
    colors: {
      main: COLORS.yellow,
      error: COLORS.errorRed,
      accent: COLORS.sage,
      body: COLORS.darkCream,
      text: COLORS.black,
      svg: COLORS.black,
      card: COLORS.darkCream,
      cardText: COLORS.black,
      background: COLORS.milk,
      slideBackground: COLORS.white,
      slideColor: COLORS.sage,
      lighterBackground: COLORS.white,
      hover: COLORS.darkCream,
      shadow: COLORS.midGray,
      border: COLORS.white,
      border2: COLORS.lightGray,
      textHover: COLORS.black,
      button: COLORS.black,
      altButton: COLORS.white,
      altButtonText: COLORS.black,
      altButtonActive: COLORS.black,
      altButtonActiveText: COLORS.white,
      altButtonBorder: 'none',
      darkButtonBg: COLORS.black,
      darkButtonText: COLORS.white,
      buttonText: COLORS.white,
      buttonHover: COLORS.orange,
      disabledButton: COLORS.lightGray,
      ring1: COLORS.yellow,
      ring2: COLORS.white,
      pageTab: COLORS.orange,
      pageTabHover: COLORS.white,
      pageTabSelected: COLORS.darkCream,
      cardContentBg: COLORS.white,
      cancelBtnBg: COLORS.black,
      cancelBtnHover: COLORS.darkGray,
      popoverBg: COLORS.darkCream,
      warningBg: COLORS.lightGray,
      warningSageBg: COLORS.sage,
      actionInfoText: COLORS.white,
      networkWarningBg: COLORS.orange,
      walletWarningBg: COLORS.milk,
      walletWarningText: COLORS.black,
      grayText: COLORS.DMMidGray,
      darkGrayText: COLORS.darkGray,
      nameText: COLORS.midGray,
      unstakeButton: COLORS.black,
      linkText: COLORS.darkSage,
      boxBorder: COLORS.midGray,
      textAlt: COLORS.black,
      textAlt2: COLORS.DMMidGray,
      selectorTextColor: COLORS.white,
      selectorBg: COLORS.black,
      borderAlt: COLORS.lightGray,
      toolTipBackground: COLORS.black,
      farmInfoBackground: COLORS.transWhite,
      inputBackground: COLORS.lightGray2,
      inputSeparator: COLORS.lightGray,
      inputActiveBg: COLORS.milk,
      inputInactiveBg: COLORS.lightGray1,
      inputErrorBg: COLORS.white,
      inputActiveBorder: COLORS.darkMilk,
      inputInactiveBorder: COLORS.offWhite,
      inputErrorBorder: COLORS.errorRed1,
      arrowColor: COLORS.darkSage,
      cardHighlight: COLORS.darkCream,
      timerColor: COLORS.DMMidGray,
      v3Gradient: `linear-gradient(to left, ${COLORS.sage}, ${COLORS.yellow});`,
    },
    images: {
      loading: loadingBlack,
    },
    svgFilter:
      'invert(4%) sepia(18%) saturate(890%) hue-rotate(2deg) brightness(93%) contrast(89%)',
    shadows,
    sizes,
  },
  Dark: {
    colors: {
      main: COLORS.yellow,
      error: COLORS.errorRed,
      accent: COLORS.darkSage,
      body: COLORS.black,
      text: COLORS.milk,
      svg: COLORS.white,
      card: COLORS.black,
      cardText: COLORS.midGray,
      background: COLORS.black,
      slideColor: COLORS.darkSage,
      slideBackground: COLORS.darkGray,
      lighterBackground: COLORS.darkGray,
      hover: COLORS.black,
      shadow: COLORS.darkGray,
      border: COLORS.DMMidGray,
      border2: COLORS.DMMidGray,
      textHover: COLORS.black,
      button: COLORS.midGray,
      buttonText: COLORS.black,
      buttonHover: COLORS.darkCream,
      altButton: COLORS.black,
      altButtonText: COLORS.white,
      altButtonActive: COLORS.white,
      altButtonActiveText: COLORS.black,
      altButtonBorder: `1px solid ${COLORS.darkGray}`,
      darkButtonBg: COLORS.black,
      darkButtonText: COLORS.white,
      disabledButton: COLORS.milk,
      ring1: COLORS.DMMidGray,
      ring2: COLORS.darkGray,
      pageTab: COLORS.darkSage,
      pageTabHover: COLORS.sage,
      pageTabSelected: COLORS.black,
      cardContentBg: COLORS.darkGray,
      cancelBtnBg: COLORS.white,
      cancelBtnHover: COLORS.darkCream,
      popoverBg: COLORS.darkGray,
      warningBg: COLORS.darkGray,
      warningSageBg: COLORS.darkSage,
      actionInfoText: COLORS.black,
      networkWarningBg: COLORS.errorRed,
      walletWarningBg: COLORS.black,
      walletWarningText: COLORS.milk,
      grayText: COLORS.midGray,
      darkGrayText: COLORS.midGray,
      nameText: COLORS.white,
      unstakeButton: COLORS.darkGray,
      linkText: COLORS.sage,
      boxBorder: COLORS.DMMidGray,
      textAlt: COLORS.white,
      textAlt2: COLORS.white,
      selectorTextColor: COLORS.black,
      selectorBg: COLORS.milk,
      borderAlt: COLORS.DMMidGray,
      toolTipBackground: COLORS.DMMidGray,
      farmInfoBackground: COLORS.transBlack,
      inputBackground: COLORS.DMMidGray,
      inputSeparator: COLORS.DMMidGray,
      inputActiveBg: COLORS.darkGray,
      inputInactiveBg: COLORS.blueGray,
      inputErrorBg: COLORS.darkGray,
      inputActiveBorder: COLORS.DMMidGray,
      inputInactiveBorder: COLORS.darkBlueGray,
      inputErrorBorder: COLORS.errorRed,
      arrowColor: COLORS.milk,
      cardHighlight: COLORS.DMMidGray,
      timerColor: COLORS.milk,
      v3Gradient: `linear-gradient(to left, ${COLORS.darkSage}, ${COLORS.yellow});`,
    },
    images: {
      loading: loadingWhite,
    },
    svgFilter:
      'invert(100%) sepia(0%) saturate(0%) hue-rotate(278deg) brightness(101%) contrast(104%)',
    shadows,
    sizes,
  },
}

export default THEME
